#!/usr/bin/env ruby

File.open("ChangeLog", "w") { |out|
  `git log -z`.split("\0").map { |chunk|
    author = chunk[/Author: (.*)/, 1].strip
    date = chunk[/Date: (.*)/, 1].strip
    desc, detail = $'.strip.split("\n", 2)
    detail ||= ""
    detail = detail.gsub(/.*darcs-hash:.*/, '')
    detail.rstrip!
    out.puts "#{date}  #{author}"
    out.puts "  * #{desc.strip}"
    out.puts detail  unless detail.empty?
    out.puts
  }
}
